appName: ingestor-server
nodeSelector: {}
affinity: {}

replicaCount: 1

imagePullSecret:
  create: false
  name: "ngc-secret"
  registry: "nvcr.io"
  username: "$oauthtoken"
  password: ""

image:
  repository: nvcr.io/nvidia/blueprint/ingestor-server
  tag: "2.2.0"
  pullPolicy: Always

server:
  workers: 1

resources:
  limits:
    memory: "25Gi"
  requests:
    memory: "25Gi"

envVars:
  EXAMPLE_PATH: 'src/nvidia_rag/ingestor_server'

  # === Vector Store Configurations ===
  APP_VECTORSTORE_URL: "http://milvus:19530"
  APP_VECTORSTORE_NAME: "milvus"
  APP_VECTORSTORE_SEARCHTYPE: "dense"
  APP_VECTORSTORE_ENABLEGPUINDEX: "True"
  APP_VECTORSTORE_ENABLEGPUSEARCH: "True"
  COLLECTION_NAME: "multimodal_data"

  # === MinIO Configurations ===
  MINIO_ENDPOINT: "rag-minio:9000"
  MINIO_ACCESSKEY: "minioadmin"
  MINIO_SECRETKEY: "minioadmin"

  # === Embeddings Configurations ===
  APP_EMBEDDINGS_SERVERURL: "nemoretriever-embedding-ms:8000"
  APP_EMBEDDINGS_MODELNAME: "nvidia/llama-3.2-nv-embedqa-1b-v2"
  APP_EMBEDDINGS_DIMENSIONS: "2048"

  # === NV-Ingest Configurations ===
  APP_NVINGEST_MESSAGECLIENTHOSTNAME: "rag-nv-ingest"
  APP_NVINGEST_MESSAGECLIENTPORT: "7670"

  # === NV-Ingest extraction configurations ===
  APP_NVINGEST_PDFEXTRACTMETHOD: "None"  # Method used for text extraction from "None", "pdfium", "nemoretriever_parse"
  APP_NVINGEST_EXTRACTTEXT: "True"  # Enable text extraction
  APP_NVINGEST_EXTRACTINFOGRAPHICS: "False"  # Enable infographic extraction
  APP_NVINGEST_EXTRACTTABLES: "True"  # Enable table extraction
  APP_NVINGEST_EXTRACTCHARTS: "True"  # Enable chart extraction
  APP_NVINGEST_EXTRACTIMAGES: "False"  # Enable image extraction
  APP_NVINGEST_TEXTDEPTH: "page"  # Extract text by "page" or "document"

  # === NV-Ingest caption configurations ===
  APP_NVINGEST_CAPTIONMODELNAME: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1"  # Model name for captioning
  APP_NVINGEST_CAPTIONENDPOINTURL: ""  # Endpoint URL for captioning model

  # === General ===
  SUMMARY_LLM: "nvidia/llama-3.3-nemotron-super-49b-v1"
  SUMMARY_LLM_SERVERURL: "nim-llm:8000"
  SUMMARY_LLM_MAX_CHUNK_LENGTH: "50000"
  SUMMARY_CHUNK_OVERLAP: "200"

  ENABLE_CITATIONS: "True"
  LOGLEVEL: "INFO"

  # === NV-Ingest splitting configurations ===
  APP_NVINGEST_CHUNKSIZE: "512"
  APP_NVINGEST_CHUNKOVERLAP: "150"
  APP_NVINGEST_ENABLEPDFSPLITTER: "True"

  # === Redis configurations ===
  REDIS_HOST: "rag-redis-master"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # === Bulk upload to MinIO ===
  ENABLE_MINIO_BULK_UPLOAD: "True"
  TEMP_DIR: "/tmp-data"

  # === NV-Ingest Batch Mode Configurations ===
  NV_INGEST_FILES_PER_BATCH: "16"
  NV_INGEST_CONCURRENT_BATCHES: "4"

# NV-Ingest
nv-ingest:
  imagePullSecrets:
    - name: "ngc-secret"
  ngcApiSecret:
    create: false
  ngcImagePullSecret:
    create: false
  image:
    repository: "nvcr.io/nvidia/nemo-microservices/nv-ingest"
    tag: "25.6.2"
  resources:
    limits:
      nvidia.com/gpu: 0
  envVars:
    INGEST_LOG_LEVEL: DEFAULT
    NV_INGEST_MAX_UTIL: 48
    INGEST_EDGE_BUFFER_SIZE: 64
    MRC_IGNORE_NUMA_CHECK: 1
    READY_CHECK_ALL_COMPONENTS: "true"
    REDIS_MORPHEUS_TASK_QUEUE: morpheus_task_queue
    NV_INGEST_DEFAULT_TIMEOUT_MS: "1234"
    MAX_INGEST_PROCESS_WORKERS: 16
    EMBEDDING_NIM_ENDPOINT: "http://nemoretriever-embedding-ms:8000/v1"
    MESSAGE_CLIENT_HOST: "rag-redis-master"
    MESSAGE_CLIENT_PORT: 6379
    MESSAGE_CLIENT_TYPE: "redis"
    MINIO_INTERNAL_ADDRESS: "rag-minio:9000"
    MILVUS_ENDPOINT: "http://milvus:19530"
    OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
    MODEL_PREDOWNLOAD_PATH: "/workspace/models/"
    INSTALL_AUDIO_EXTRACTION_DEPS: "true"

    # WAR to fix -loadbalancer from the ingestion NIMs URLs
    PADDLE_GRPC_ENDPOINT: nv-ingest-paddle:8001
    PADDLE_HTTP_ENDPOINT: http://nv-ingest-paddle:8000/v1/infer
    PADDLE_INFER_PROTOCOL: grpc
    YOLOX_GRPC_ENDPOINT: nemoretriever-page-elements-v2:8001
    YOLOX_HTTP_ENDPOINT: http://nemoretriever-page-elements-v2:8000/v1/infer
    YOLOX_INFER_PROTOCOL: grpc
    YOLOX_GRAPHIC_ELEMENTS_GRPC_ENDPOINT: nemoretriever-graphic-elements-v1:8001
    YOLOX_GRAPHIC_ELEMENTS_HTTP_ENDPOINT: http://nemoretriever-graphic-elements-v1:8000/v1/infer
    YOLOX_GRAPHIC_ELEMENTS_INFER_PROTOCOL: grpc
    YOLOX_TABLE_STRUCTURE_GRPC_ENDPOINT: nemoretriever-table-structure-v1:8001
    YOLOX_TABLE_STRUCTURE_HTTP_ENDPOINT: http://nemoretriever-table-structure-v1:8000/v1/infer
    YOLOX_TABLE_STRUCTURE_INFER_PROTOCOL: grpc

  paddleocr-nim:
    deployed: true
    replicaCount: 1
    image:
      repository: nvcr.io/nim/baidu/paddleocr
      tag: "1.3.0"
    imagePullSecrets:
    - name: ngc-secret
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1

  nemoretriever-graphic-elements-v1:
    deployed: true
    replicaCount: 1
    image:
      repository: nvcr.io/nim/nvidia/nemoretriever-graphic-elements-v1
      tag: "1.3.0"
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1

  nemoretriever-page-elements-v2:
    deployed: true
    replicaCount: 1
    image:
      repository: nvcr.io/nim/nvidia/nemoretriever-page-elements-v2
      tag: "1.3.0"
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1

  nemoretriever-table-structure-v1:
    deployed: true
    replicaCount: 1
    image:
      repository: nvcr.io/nim/nvidia/nemoretriever-table-structure-v1
      tag: "1.3.0"
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1

  nim-vlm-text-extraction:
    image:
      repository: "nvcr.io/nim/nvidia/nemoretriever-parse"
      tag: "1.2"
    deployed: false

  nim-vlm-image-captioning:
    deployed: false

  nvidia-nim-llama-32-nv-embedqa-1b-v2:
    image:
      repository: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2
      tag: "1.6.0"
    deployed: false

  milvus:
    image:
      all:
        repository: milvusdb/milvus
        tag: v2.5.3-gpu
        pullPolicy: IfNotPresent
    standalone:
      resources:
        limits:
          nvidia.com/gpu: 1
    fullnameOverride: "milvus"
  otelDeployed: false
  zipkinDeployed: false
